-- SQLite
DROP TABLE IF EXISTS contato;

CREATE TABLE contato(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    mensagem TEXT NOT NULL
);

SELECT * FROM contato